### ISSUE TITLE
After getting error message "You need to select a file before uploading!" if you select a file the error message is not hiding form the view 

### ISSUE THREAD

**Issue by Kallyan01** [Kallyan01/fileuploader#26]

**Comment by mjmanas54** [comment]
I had opened a pull request in which I had solved this issue please review my PR.

**Comment by mjmanas54** [comment]
If there is any conflict in my PR please suggest and assign this issue to me.

**Comment by mjmanas54** [comment]
[https://github.com/Kallyan01/fileuploader/pull/43](url)
